# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'EWScrollViewVerticalBar' do
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!

  # Pods for EWScrollViewVerticalBar
  pod "EWScrollViewVerticalBar", :path => "../"
end
